version: '3.7'
services:
  rabbitmq:
    build: .
    hostname: app-rabbitmq
    tty: true
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq/mnesia
    environment:
      RABBITMQ_ERLANG_COOKIE: 6085e2412b6fa88647466c6a81c0cea0
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /
  producer:
    image: node:latest
    volumes:
      - ./node-app:/opt/app
    command: node /opt/app/producer.js
    depends_on:
      - rabbitmq
  consumer:
    image: node:latest
    volumes:
      - ./node-app:/opt/app
    command: node /opt/app/consumer.js
    depends_on:
      - rabbitmq
  nginx:
    image: nginx:latest
    ports:
      - "1313:8080"
      - "15672:15672"
    volumes:
      - ./nginx/lb.conf:/etc/nginx/conf.d/lb.conf
    depends_on:
      - rabbitmq
      - server
  server:
    image: node:latest
    volumes:
      - ./node-app:/opt/app
    command: node /opt/app/server.js
    